name: theme_definition
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  localization_builder: ^0.9.7
  yaml: ^3.0.0
  recase: ^4.0.0-nullsafety.0
  equatable: ^2.0.0-nullsafety.3

dependency_overrides:
  yaml: ^3.0.0
  recase: ^4.0.0-nullsafety.0
  equatable: ^2.0.0-nullsafety.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
